-- Mix of Technical, General Knowledge, and Campus-style questions
INSERT INTO questions (question_text, option_a, option_b, option_c, option_d, correct_option) VALUES
('Which data structure uses the LIFO (Last In First Out) principle?', 'Queue', 'Linked List', 'Stack', 'Array', 'C'),
('Who is known as the father of the World Wide Web?', 'Bill Gates', 'Tim Berners-Lee', 'Steve Jobs', 'Mark Zuckerberg', 'B'),
('What does "HTTP" stand for in web addresses?', 'HyperText Transfer Protocol', 'HyperText Technical Process', 'High Transfer Text Protocol', 'Hyperlink Total Transfer Protocol', 'A'),
('Which programming language is predominantly used for Android App development?', 'Swift', 'Kotlin', 'Objective-C', 'C#', 'B'),
('In computing, what does "RAM" stand for?', 'Read Access Memory', 'Random Access Memory', 'Ready Active Module', 'Rapid Access Memory', 'B'),
('Which of these is NOT an operating system?', 'Linux', 'Windows', 'Oracle', 'macOS', 'C'),
('What is the chemical symbol for Gold?', 'Ag', 'Fe', 'Au', 'Gd', 'C'),
('Which planet is known as the Red Planet?', 'Venus', 'Mars', 'Jupiter', 'Saturn', 'B'),
('Who painted the "Mona Lisa"?', 'Vincent van Gogh', 'Pablo Picasso', 'Leonardo da Vinci', 'Claude Monet', 'C'),
('What is the capital of Japan?', 'Seoul', 'Beijing', 'Tokyo', 'Bangkok', 'C'),
('Which organ in the human body filters blood?', 'Heart', 'Lungs', 'Kidneys', 'Liver', 'C'),
('What is the largest ocean on Earth?', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean', 'Pacific Ocean', 'D'),
('Who wrote the play "Romeo and Juliet"?', 'Charles Dickens', 'William Shakespeare', 'Mark Twain', 'Jane Austen', 'B'),
('What is the square root of 144?', '10', '11', '12', '13', 'C'),
('Which gas do plants absorb from the atmosphere for photosynthesis?', 'Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen', 'C'),
('What is the currency of the United Kingdom?', 'Euro', 'Dollar', 'Pound Sterling', 'Yen', 'C'),
('Which is the smallest prime number?', '0', '1', '2', '3', 'C'),
('What is the main component of natural gas?', 'Ethane', 'Propane', 'Butane', 'Methane', 'D'),
('In which year did the Titanic sink?', '1905', '1912', '1918', '1923', 'B'),
('What is the hardest natural substance on Earth?', 'Gold', 'Iron', 'Diamond', 'Graphite', 'C'),
('Which company developed the Java programming language?', 'Microsoft', 'Sun Microsystems', 'Apple', 'IBM', 'B'),
('What does SQL stand for?', 'Simple Query Language', 'Structured Query Language', 'System Quality Log', 'Standard Query Logic', 'B'),
('Which layer of the Earth is liquid?', 'Crust', 'Mantle', 'Outer Core', 'Inner Core', 'C'),
('Who was the first person to walk on the moon?', 'Yuri Gagarin', 'Buzz Aldrin', 'Neil Armstrong', 'John Glenn', 'C'),
('What is the most spoken language in the world?', 'English', 'Spanish', 'Mandarin Chinese', 'Hindi', 'C'),
('Which country is known as the Land of the Rising Sun?', 'China', 'South Korea', 'Japan', 'Thailand', 'C'),
('What is the boiling point of water at sea level?', '90°C', '100°C', '110°C', '120°C', 'B'),
('Which element has the atomic number 1?', 'Helium', 'Oxygen', 'Hydrogen', 'Carbon', 'C'),
('Who discovered gravity?', 'Albert Einstein', 'Isaac Newton', 'Galileo Galilei', 'Nikola Tesla', 'B'),
('What is the largest mammal in the world?', 'Elephant', 'Blue Whale', 'Giraffe', 'Shark', 'B');
